### DISCUSSION TITLE
How to mention GITHUB_ACTOR via SLACK_MESSAGE

### DISCUSSION THREAD

**Discussion by theguptaji** [rtCamp/action-slack-notify#103] [Q&A]
Hi, 
we are trying to overwrite the default `SLACK_MESSAGE` by changing from plain text to mention the person who pushed the code `($GITHUB_ACTOR as per the docs)` like this:
```
- name: Slack Notification on Success
              if: ${{ success() }}
              uses: rtCamp/action-slack-notify@v2.0.2
              env:
                  SLACK_CHANNEL: cicd_notification
                  SLACK_MSG_AUTHOR: $GITHUB_ACTOR
                  SLACK_LINK_NAMES: true
                  SLACK_MESSAGE: 'Hello ${{SLACK_MSG_AUTHOR}}'
```
But we are unable to get in on the slack. Please let us know what is a proper way to mention a user via `SLACK_MESSAGE`. thanks
