### DISCUSSION TITLE
notification on only failed actions

### DISCUSSION THREAD

**Discussion by aditya-jeeves** [rtCamp/action-slack-notify#140] [General]
Hi Awesome Team,

may I know how to configure this for just failed builds?

**Comment by maan-maker** [comment]
Use the `if: ${{ failure() }}` expression:
https://docs.github.com/en/actions/learn-github-actions/expressions#failure

Example:
```
- name: Send Slack notification on failure
  uses: rtCamp/action-slack-notify@v2
  env:
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  if: ${{ failure() }}
```
