### DISCUSSION TITLE
Using this via docker run ?

### DISCUSSION THREAD

**Discussion by pascalandy** [rtCamp/action-slack-notify#64] [Q&A] [answered]
This github action is very elegant!

```
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: general
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Post Title
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
```

**Question**: Do you guys have a `docker run` version of this app ? At the moment I use `noti` but you provide more features :-p
