### ISSUE TITLE
Slack Desktop Pop-Up Notification Shows Incorrect Information

### ISSUE THREAD

**Issue by davidgourde** [rtCamp/action-slack-notify#111]
The information is correct on the notification itself (the message in the channel), but the pop-up notification is incorrect.

What is incorrect:
- The SLACK_ICON is not used. Instead, it shows a grey icon. It should show the SLACK_ICON.
- The sender is incorrect. It shows the SLACK_MSG_AUTHOR (GitHub user that pushed the commit/action) instead of the SLACK_USERNAME. This is a mistake, as we want to see the notification come from our bot, not from a random user.

Here is an example:
![image](https://user-images.githubusercontent.com/77303785/135165175-7bcd9efa-50f6-44c0-b8ec-aac9f7dc7595.png)

Here are the env variables I used to customize the notification:

```
uses: rtCamp/action-slack-notify@v2
env:
  SLACK_WEBHOOK: "something"
  SLACK_MESSAGE: "something"
  SLACK_TITLE: "something"
  SLACK_COLOR: "something"

  MSG_MINIMAL: commit,actions url
  SLACK_FOOTER: ""
```
