### ISSUE TITLE
SLACK_ICON_EMOJI randomly displayed

### ISSUE THREAD

**Issue by schmidtsonian** [rtCamp/action-slack-notify#122]
I'm using custom emojis but for some reason they are not displayed every time

```
      - name: Slack Notification (Success)
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: drone
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON_EMOJI: ':cicd_success_1:'
          SLACK_USERNAME: <Add client/project name>
          SLACK_WEBHOOK: ***
          SLACK_FOOTER: <Add staging URL and/or storybook URL>
      
      - name: Slack Notification (Failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: drone
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON_EMOJI: ':facepalm:'
          SLACK_USERNAME: <Add client/project name>
          SLACK_WEBHOOK: ***
          SLACK_FOOTER: Sorry Mate

      - name: Slack Notification (Cancelled)
        if: cancelled()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: drone
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON_EMOJI: ':troll:'
          SLACK_USERNAME: <Add client/project name>
          SLACK_WEBHOOK: ***
          SLACK_FOOTER: You shall not pass
```

![Screen Shot 2022-04-09 at 16 50 39](https://user-images.githubusercontent.com/2094546/162592620-3dc300c0-1108-4341-9eca-d071f78918b6.png)
