### ISSUE TITLE
[Question] Create mention when a deploy happens

### ISSUE THREAD

**Issue by josh803316** [rtCamp/action-slack-notify#123]
Is there a way to enable slack mentions via this github action. I created a Github <-> Slack integration by doing `/github login` in slack for the user (github.actor) as a way to test, but it didn't seem to work. I did see my github username in the post but it didn't seem to do the mention part.

```yaml
env:
          ....
          SLACK_MESSAGE: 'Deployed ${{ github.head_ref }} to staging :rocket: <@${{ github.actor }}>'
          ...
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEPLOYMENT }}
```
