### ISSUE TITLE
Slack message trigger 3 times 

### ISSUE THREAD

**Issue by pastequeninja** [rtCamp/action-slack-notify#136]
Do you wondering why I received 3 messages from bot wehn I publish a release ? Thanks

```
on: release
name: New release
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Username
          SLACK_ICON: https://www.google.com/
          SLACK_TITLE: I've published a new release 🚀
          SLACK_COLOR: ${{ job.status }}
```

**Comment by L0RD-ZER0** [comment]
This appears to be an issue with your workflow configuration. As stated by [GitHub's Documentation about the Release Trigger Event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release), you'll receive a variety of events upon publishing your package. To mitigate this issue, you might want to try filtering the events the action runs on using filtering syntax provided by GitHub Actions:

```yaml
on:
  event:
    types: [type-to-filter, ...]
```

Therefore, for the particular use case of filtering an event to send a message on 'publish' of a package, you can use something along the lines of the following:

```yaml
on:
  release:
    types: [published]
```
