### ISSUE TITLE
Does this action impact subsequent success() or failure() or overall job status?

### ISSUE THREAD

**Issue by winzig** [rtCamp/action-slack-notify#14]
I'd like to use this action to notify Slack if one of my steps fails, like so:

```
    - name: Slack Notify dotnet-build Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v1.0.0
      env: 
        SLACK_TITLE: ":rotating_light: dotnet-build Failure"
        SLACK_MESSAGE: "My failure message..."
```

This would be the last step in one of my jobs, and I have another job that relies on this first job with `needs`. What I'm wondering is if `failure()` is true, and this action to notify Slack runs and succeeds, is the exit code for this job considered a success (due to the Slack notification), or a failure (due to the step that failed prior to the Slack notification)?
