### ISSUE TITLE
Support specific ref passed on workflow_dispatch input

### ISSUE THREAD

**Issue by GroJooo** [rtCamp/action-slack-notify#176]
Hi,
Thanks for the hard work !

I'm having a particular use case here:
- I'm manually running my workflow using workflow_dispatch
- I have defined a **commitSpecific** optional input which permits to pass a specific SHA-1 ref to my worflow instead oh HEAD

In this case, I'm unable to change the ref passed to action-slack-notif so it can be overriden in the Slack Notif "commit" field.

Is there a way to work around this ?

Below a fraction of my YAML file:

```
on:
  workflow_dispatch:

    inputs:
        
      environment:
        required: true
        default: 'test'
        type: choice
        description: Which environment ?
        options:
          - test
          - staging
          - prod
      
      build_assets:
        required: false
        type: boolean
        description: Build assets ?

      commitSpecific:
        required: false
        type: string
        description: Specify cutom SHA-1 commit hash (Optional)

 jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Project Checkout Latest
      if: ${{ inputs.commitSpecific == '' }}
      uses: actions/checkout@v3

    - name: Project Checkout Specific
      if: ${{ inputs.commitSpecific != '' }}
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.commitSpecific }}

    - name: Job Start Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: GitHub Actions
        SLACK_COLOR: '#FFFF33'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'Job started on ${{ inputs.environment }} env with assets deploy : ${{ inputs.build_assets }}'
        SLACK_FOOTER: ''

```
