### ISSUE TITLE
Hey 👋🏻, I'm trying for a quite some time now to send a file using this Slack Action.

### ISSUE THREAD

**Issue by Pedro-Ivo-Neves** [rtCamp/action-slack-notify#178]
Hey 👋🏻, I'm trying for a quite some time now to send a file using this Slack Action.

Here's the code.

```yaml
name: 'Slack Notification Test'

on:
  push:
    branches:
      - main

jobs:
    slack_notification:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout ⚙️
              uses: actions/checkout@v3


            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2.3.0
              env:
                SLACK_CHANNEL: testes-de-automations
                SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
                SLACK_ICON: https://github.com/rtCamp.png?size=48
                SLACK_MESSAGE: ${{ GITHUB.event.commits.message }}
                SLACK_TITLE: 'Commit from: ${{ github.repository }}'
                SLACK_USERNAME: ${{ github.actor}}
                SLACK_FILE_UPLOAD: .github/workflows/test.txt
                SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
                # SLACK_WEBHOOK: ${{ secrets.SLACK_KEY_URL }}
```

And it gives me the following answer

![image](https://github.com/rtCamp/action-slack-notify/assets/83455817/87aef6e4-67e6-4c29-a280-6fdd23e8864a)

But it doesn't send the file neither the message.

Can someone help?

_Originally posted by @Pedro-Ivo-Neves in https://github.com/rtCamp/action-slack-notify/discussions/177_
