### ISSUE TITLE
`SLACK_ICON_EMOJI` not displaying correctly in some situations

### ISSUE THREAD

**Issue by MatthewCane** [rtCamp/action-slack-notify#179]
Firstly, thank you for this Action, I've been using this extensively and it's been awesome.

The issue I am facing is that the `SLACK_ICON_EMOJI` is working inconsistently for me. The relevant part of my workflow is:

```yaml
jobs:
  notify:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.slack_webhook}}
          SLACK_USERNAME: Actions Bot
          SLACK_ICON_EMOJI: ${{ inputs.status == 'success' && ':rocket:' || ':siren:' }}
          SLACK_LINK_NAMES: true
          SLACK_COLOR: ${{ inputs.status }}
          SLACK_TITLE: ${{ inputs.title }}
          SLACK_MESSAGE: ${{ inputs.message }}
```

I am using the ternary operator as found in the [Actions documentation](https://docs.github.com/en/actions/learn-github-actions/expressions#example) to set the icon emoji depending on the `inputs.status` value which is either `success` or `failure`. When the status is `success` it displays the icon as  🚀 as expected, however when it is any other value it displays a generic icon.

I know the status is being passed correctly, because it has an effect on the `SLACK_COLOR` variable. I can also see it in the workflow log:

```
> Run rtCamp/action-slack-notify@v2
  env:
    SLACK_WEBHOOK: ***
    SLACK_USERNAME: Actions Bot
    SLACK_ICON_EMOJI: :siren:
    SLACK_LINK_NAMES: true
    SLACK_COLOR: failure
    SLACK_TITLE: Continuous Deployment Failure
    SLACK_MESSAGE: The CD process has failed. Please check the workflow for more information.
```

Is there anything I can do to resolve this? I can't understand why it isn't working as expected.

Thanks!
