### ISSUE TITLE
[ERROR] Secret `SLACK_WEBHOOK` is missing. Falling back to using `SLACK_TOKEN` and `SLACK_CHANNEL`.

### ISSUE THREAD

**Issue by bbednarek** [rtCamp/action-slack-notify#191]
The `SLACK_WEBHOOK` which is mentioned in the [docs](https://github.com/rtCamp/action-slack-notify?tab=readme-ov-file#usage) is deprecated. 
<img width="1036" alt="Screenshot 2024-07-08 at 17 58 48" src="https://github.com/rtCamp/action-slack-notify/assets/895578/5c4696ff-9662-4fbb-b1c0-8e444f8023ec">

We supply `SLACK_TOKEN` 
```
SLACK_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
```
however when we run the pipeline there is an error
```
[ERROR] Secret `SLACK_WEBHOOK` is missing. Falling back to using `SLACK_TOKEN` and `SLACK_CHANNEL`.
```

The message is pushed to the slack channel, but because we have `if: failure()`
```
- name: Notify Slack Channel
  if: failure()
  uses: rtCamp/action-slack-notify@v2
  env:
    SLACK_CHANNEL: example-channel
    SLACK_COLOR: '#db540b'
    SLACK_MESSAGE: "Example message"
    SLACK_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
```
it always send the notification, even though there is no failure.
