### ISSUE TITLE
SLACK_MESSAGE becomes EOM when SLACKIFY_MARKDOWN is true

### ISSUE THREAD

**Issue by x-dune** [rtCamp/action-slack-notify#203]
Since the release of [v2.3.1](https://github.com/rtCamp/action-slack-notify/releases/tag/v2.3.1), the `SLACK_MESSAGE` becomes EOM when `SLACKIFY_MARKDOWN` is set to true

Reproducible with this workflow
```yml
name: test

on:
    workflow_dispatch:

jobs:
    slack_message_test:
        name: Slack Message
        runs-on: ubuntu-latest
        steps:
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2.3.1
              env:
                  SLACK_CHANNEL: {{ your slack channel }}
                  SLACK_COLOR: ${{ job.status }}
                  SLACK_MESSAGE: 'test message'
                  SLACK_TITLE: 'test'
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                  SLACKIFY_MARKDOWN: true
                  MSG_MINIMAL: true

```
Removing `SLACK_COLOR: ${{ job.status }}` seems to fix the issue
