### ISSUE TITLE
Icon Emoji not working

### ISSUE THREAD

**Issue by pReya** [rtCamp/action-slack-notify#21]
No matter what syntax I chose, the Icon Emoji is never being shown. I tried `house`, `:house:` and `':house:'` without success. Any idea for the reason? Did Slack change anything on their side?

```
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_CHANNEL: teg-baugebiets-map
        SLACK_ICON_EMOJI: ':house:'
        SLACK_MESSAGE: 'New version: https://blabla/index.html'
        SLACK_TITLE: 'Hausbau'
        SLACK_USERNAME: The Architect
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
```
