### ISSUE TITLE
SLACK_THREAD_TS not working

### ISSUE THREAD

**Issue by kishore-vkrn** [rtCamp/action-slack-notify#210]
Hi,

From README for I got 

> f you want to send message in a thread, you can pass the timestamp of the parent message to this variable. You can get the timestamp of the parent message from the message URL in Slack. (ex: SLACK_THREAD_TS: 1586130833.000100)

But still not clear how would I get the timestamp of the parent mesage. Looking at slack api ts seems a better output but when I tried I get separate messages not in threads

```yml

jobs:
  send-slack-notification:
    runs-on: [ Standard, self-hosted, X64, ubuntu ]
    needs: [validate-inputs]
    steps:
      - name: Notify Slack - Deployment Started
        id: slack-notify
        uses: actions/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "*» ${{ github.event.inputs.env }}* deployment started. _${{ github.event.inputs.tag }}_"
          MSG_MINIMAL: actions url, commit
          SLACK_FOOTER: ""
          SLACK_COLOR: ${{ job.status }} 
          
  ec2-deployment:
    needs: [send-slack-notification]
    runs-on: [ Standard, self-hosted, X64, ubuntu ]
    steps:
      - name: Notify Slack - Deployment status
        uses: actions/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: actions url, commit
          SLACK_MESSAGE: "*» ${{ github.event.inputs.env }}*. deployment status  → ${{ job.status }}"
          SLACK_FOOTER: ""
          SLACK_COLOR: ${{ job.status }}
          SLACK_THREAD_TS: "${{ needs.slack-notify.outputs.ts }}"
```
 
Better documentation or on how to use this will be appreciated.
