### ISSUE TITLE
Is there an option to disable the default icon?

### ISSUE THREAD

**Issue by th0th** [rtCamp/action-slack-notify#32]
First, thank you for making this action available to us all 💐

Slack enables setting an icon for the incoming message on the webhook con figuration and I want to use the icon I set there, instead of the action's default. Is there an option for that?

**Comment by mrrobot47** [comment]
Please check this: https://github.com/rtCamp/action-slack-notify#environment-variables

You can provide your custom icon or any slack emoji via env variables.

**Comment by th0th** [comment]
I am aware of that option. What I am asking is, I want **not to have a custom icon and use the predefined icon on the Slack options**.

**Comment by mrrobot47** [comment]
You can configure:

```
SLACK_ICON_EMOJI: ":slack:"
```

Configure the predefined icon or image in this action via env variables. 

This is because, by default this action is setting up `SLACK_ICON` (`Default` section in env vars table), the only way to override it, is to change it by the value that you want. Set your desired emoji using `SLACK_ICON_EMOJI` or image via a url in `SLACK_ICON`.

**Comment by th0th** [comment]
On the "Incoming Webhooks" configuration, Slack enables you to set an icon. But [here](https://github.com/rtCamp/action-slack-notify#environment-variables) the default is shown as a "rt circle" icon. What I am trying to do is that I don't want to set a custom icon in this action, I don't want this action to override the icon I set on the Slack's "Incoming Webhooks" settings. I want to use the icon I set on the Slack.

Here is the screenshot of the relevant part on the Slack's "Incoming Webhook" configuration:

<img width="972" alt="Screen Shot 2020-06-15 at 17 22 59" src="https://user-images.githubusercontent.com/698079/84668934-e3978000-af2c-11ea-8a86-8afb409e32fd.png">

**Comment by mrrobot47** [comment]
I will add this to feature request.

For now, just upload the image you have configured in slack webhook somewhere, you can even upload it in the GitHub issue, right here. Get the url of that image from the issue and use it in the action by passing it to the `SLACK_ICON` env variable.

**Comment by pmdaly** [comment]
Any update on this?

**Comment by scorphus** [comment]
@th0th: what would you say if I suggested you to reopen this issue?

@mrrobot47: any updates? Would you accept a PR? Could you please provide an overview of what needs to be done?

Thanks!

**Comment by th0th** [comment]
@scorphus I don't see an option to re-open, sorry :/

**Comment by mrrobot47** [comment]
@pmdaly @th0th @scorphus in the env vars please try the following:

```yml
SLACK_ICON: false
```

Complete workflow example:
```yml
on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: false
```

If it is set to `false`, it should pick up the icon you have configured in the webhook settings.

---

Optionally, do check env vars: https://github.com/rtCamp/action-slack-notify/#environment-variables
You can use `SLACK_ICON`/`SLACK_ICON_EMOJI` to customize the icon from the action itself as well.
