### ISSUE TITLE
Feature request: ability to hide ref, event, and action URL

### ISSUE THREAD

**Issue by cbetta** [rtCamp/action-slack-notify#33]
I'd love to be able to slim down the messages being sent. I don't really need the `Ref`, `Event` and `Action URL` in most cases. Can we add an option to hide these? Or maybe to collapse them somehow to take up less space in a channel?

**Comment by mrrobot47** [comment]
Have provisioned an env variable `MSG_MINIMAL` to get the minimal message. Checkout: https://github.com/rtCamp/action-slack-notify/#environment-variables

As this has not yet been released, you will have to use `@master` to get the fix.
Update your action to look like:
```yml
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_MESSAGE: "message"
        MSG_MINIMAL: true
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
```
