### ISSUE TITLE
How to trigger the slack notification manually

### ISSUE THREAD

**Issue by rrfunde** [rtCamp/action-slack-notify#44]

**Comment by mrrobot47** [comment]
Manually as in? Manually from GitHub actions or do you want to run it from your local machine?

**Comment by rrfunde** [comment]
see, I want to send slack notification conditionally. for example, I have build/deply jobs inside a workflow, so i only wanna send slack notification if the branch is master then send otherwise dont

**Comment by mrrobot47** [comment]
Please go through [events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows) GitHub doc.

Particularly for your use case check [this](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration).

```yml
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
```
