### ISSUE TITLE
How to change SLACK_COLOR on success, cancelled, or failure?

### ISSUE THREAD

**Issue by mitchdowney** [rtCamp/action-slack-notify#48]
Sorry for such a basic question, but any help would be appreciated. I'm trying to make the slack notification change colors depending on the Github Action's success, cancellation, or failure.

The following seems to work for me:

```
    - name: Slack Notification - Success
      if: success()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Slack Notification - Failure
      if: cancelled() || failure()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: 'danger'
```

But is there a more efficient way to write this? Seems like a lot of code just to change color. I'm not seeing a way to use if conditionals to change `env` values...otherwise I would set `SLACK_COLOR` to `good` or `danger` if success/cancel/failure.
