### ISSUE TITLE
Can I use env var in SLACK_TITLE?

### ISSUE THREAD

**Issue by son** [rtCamp/action-slack-notify#51]
```
      - uses: actions/checkout@v2
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: 'https://xxxx'
          SLACK_TITLE: ':rocket:【Android】App Tester:rocket:\nバージョン: v${VERSION}(${BUILD_NUMBER})\nリリースノート:\n${RELEASE_NOTE}'
```
