### ISSUE TITLE
QUESTION: Notify on Action pass, fail, change in status

### ISSUE THREAD

**Issue by jeffpaul** [rtCamp/action-slack-notify#61]
Is this action able to notify into Slack when another action run passes, fails, or when another action changes from passing to failing or failing to passing?  If so, could you provide an example?

**Comment by mrrobot47** [comment]
Hey @jeffpaul :wave: 

>when another action run passes, fails

This is possible, but probably not what you want. Having this action inside your workflow will give additional information like the link to your passed/failed workflow so you can check the logs, also adds many other details that are helpful by default.

You can add this action in the existing action workflow and configure it such that it will notify on success as well as failure.

In your existing action workflow, you can add the following:
```yml
    - name: Slack Notification
      if: always()
      uses: rtcamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
```

`if: always()`, which is configured in the above example will make sure that the slack notification runs no regardless of the fact that the workflow passes/fails. 
You can change it to `if: success()` for getting notification only on success.
Or to `if: cancelled() || failure()` for getting notification when the workflow is cancelled or fails.

Let me know if this helps?
