### ISSUE TITLE
Add Test Results as SLACK_MESSAGE

### ISSUE THREAD

**Issue by estefafdez** [rtCamp/action-slack-notify#65]
Hi, 

is there any way to add a custom message on slack with the Tests Results executed on the job? 

I saved the results on a JSON file and I can easily do a cat on the file to see the results in plain text, but I couldn't find a way to display this message as SLACK_MESSAGE. 

Is there an easy way to do it? Thanks!

**Comment by mrrobot47** [comment]
You can get the output of json file and pass it to the slack action using the [`set-output command`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter).

Example:
```yml
    - id: vars
      run: |
          echo ::set-output name=testResult::$(cat $PATH_TO_JSON_FILE)

    - name: Slack Notification
      uses: rtcamp/action-slack-notify@v2
      env:
        SLACK_MESSAGE: ${{ steps.vars.outputs.testResult }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

```
