### ISSUE TITLE
Error sending message: Post "***": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by jupe** [rtCamp/action-slack-notify#66]
version: rtcamp/action-slack-notify:v2.1.2
runs-on: ubuntu-latest
workflow triggered by `workflow_dispatch` (manually)

For some reason I get this kind of error:
```
Error sending message: Post "***": unsupported protocol scheme ""
```
I've defined step like this:

```
- name: Slack Notification
  uses: rtCamp/action-slack-notify@v2
  env:
    SLACK_CHANNEL: 'test'
    SLACK_MESSAGE: ':rocket:'
    SLACK_TITLE: 'test'
    SLACK_USERNAME: CI-bot
    SLACK_WEBHOOK: ${{ secrets.SLACK_BOT_TOKEN }}
```

secret and channel should be valid. Any idea what could be wrong?
