### ISSUE TITLE
SLACK_MESSAGE is null when Trigger is On - Release Type [Published]

### ISSUE THREAD

**Issue by devinci** [rtCamp/action-slack-notify#69]
I'm attempting to notify our dev group when a release is made to also include the release notes. I have the trigger tied to the release and the release notes generate for the linked tag. However the release notes do not show in the `SLACK_MESSAGE`. Is there a specific way this needs to be configured that you could provide me an example of?

**workflow.yml:**
```
name: Release Notification
on:
  release:
    types: [published]
jobs:
  slackNotification:
    name: Release Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: Release Notification
        SLACK_WEBHOOK: ${{ secrets.SLACK_RELEASE_URL }}

```
**Github Release Notes:**
![image](https://user-images.githubusercontent.com/7167770/104934268-9e4f9b00-59b2-11eb-93d8-59ad18b9ffb3.png)

**Slack Notification:**
![image](https://user-images.githubusercontent.com/7167770/104934084-647e9480-59b2-11eb-8652-383539b3f441.png)

**Comment by mrrobot47** [comment]
Hey @devinci, 

By default, this action defaults [`SLACK_MESSAGE` to the commit message](https://github.com/rtCamp/action-slack-notify#environment-variables). But, in the case of release publish event, there is no commit message associated, hence it outputs null.

To get the release notes, you can use data from [`GITHUB_EVENT_PATH`](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables).

Here is an example of how you could do it:

```yml
name: Release Notification
on:
  release:
    types: [published]
jobs:
  slackNotification:
    name: Release Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - id: vars
      run: |
          releaseNotes="$(cat $GITHUB_EVENT_PATH | jq -r .release.body)"
          releaseNotes="${releaseNotes//'%'/'%25'}"
          releaseNotes="${releaseNotes//$'\n'/'%0A'}"
          releaseNotes="${releaseNotes//$'\r'/'%0D'}"
          echo ::set-output name=releaseNotes::"$releaseNotes"

    - name: Release Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: Release Notification
        SLACK_MESSAGE: ${{ steps.vars.outputs.releaseNotes }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
```

Note that before setting the output, escaping is done so that it does not truncate the release notes. [Reference to the issue on why it is needed](https://github.community/t/set-output-truncates-multiline-strings/16852).

Lastly, at the moment this will give you the release notes in slack as is, that is, the markdown will be displayed in the message. It is planned to add support for converting markdown to slack formatting for pretty-printing things like this. You can watch this repo to get notified regarding when that is released.
