### ISSUE TITLE
Not pulling secrets

### ISSUE THREAD

**Issue by lavanyach1** [rtCamp/action-slack-notify#71]
I have the `SLACK_WEBHOOK` var configured in Secrets. I am trying to use this 

```
        env:
          SLACK_MESSAGE: 'Post Content: Testing slackNotifications from github-actions.'
          SLACK_CHANNEL: '#test'
          SLACK_USERNAME: github-actions-test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
```

If I have the webhook url hard-coded it works fine, if i try to pull it from secrets, it throws this error. Any thoughts why?

`Secret `SLACK_WEBHOOK` is missing. Please add it to this action for proper execution.`

**Comment by lavanyach1** [comment]
Nevermind!! I had to have the envs before using the action. :) It works fine when I do the following:

```
      - name: Slack Notification
        env:
          SLACK_MESSAGE: ${{env.WORKFLOW_CONCLUSION}}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: rtCamp/action-slack-notify@v2
```
