### ISSUE TITLE
Slack Message is Null when slack-notify is triggered with pull request event

### ISSUE THREAD

**Issue by ta185044** [rtCamp/action-slack-notify#74]
It seems this github action only support using GITHUB_SHA, is there a way to work with the pull request head SHA.

![slack-notify-null-message](https://user-images.githubusercontent.com/67597491/110111353-27982100-7deb-11eb-88ef-5c85016e2852.png)

using v2.1.2

**Comment by mrrobot47** [comment]
On `pull_request` event, you can not get the commit message directly. Ref: https://github.community/t/accessing-commit-message-in-pull-request-event/17158

To get the commit message with this action during `pull_request` event, you can use the following workaround (fetch the commit message before running slack notification action and passing on the message using output):
```yml

    - name: Checkout Project
      uses: actions/checkout@v2
      with:
        # We need to fetch with a depth of 2 for pull_request so we can do HEAD^2
        fetch-depth: 2

    - name: "[Pull Request] Get commit message"
      if: github.event_name == 'pull_request'
      id: pr_get_commit_message
      run: echo ::set-output name=pr_commit_message::$(git log --format=%B -n 1 HEAD^2)

    - name: Slack Notification
      uses: docker://ghcr.io/rtcamp/action-slack-notify:develop
      env:
        SLACK_MESSAGE: ${{ steps.pr_get_commit_message.outputs.pr_commit_message }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
```
