### ISSUE TITLE
Drop default values of SLACK_ICON & SLACK_USERNAME

### ISSUE THREAD

**Issue by Pyppe** [rtCamp/action-slack-notify#76]
Currently the plugin sets default values for these:
```
export SLACK_ICON=${SLACK_ICON:-"https://avatars0.githubusercontent.com/u/43742164"}
export SLACK_USERNAME=${SLACK_USERNAME:-"rtBot"}
```

IMHO it would be better to leave them empty, in which case Slack would use the values defined in the webhook itself:
![image](https://user-images.githubusercontent.com/503168/110291665-d65b7d80-7ff4-11eb-8b57-fd55fbe374bc.png)

**Comment by bogaertg** [comment]
#79 
Can you review it ?

**Comment by Pyppe** [comment]
Do you mean me? :)

If so: yes, the bash script looks fine! 🙌  However, I'm not familiar with Go, so I cannot vouch how the end-to-end functionality works.

Do you know if it is possible to run the specific pull-request in our GitHub workflow? I could verify it that way.

**Comment by bogaertg** [comment]
I update action.yml for testing.
You can use
```
- name: Slack Notification
   uses: bogaertg/action-slack-notify@fix/remove-default-value-slack-webhook
```

**Comment by Pyppe** [comment]
![image](https://user-images.githubusercontent.com/503168/111451968-ac076f80-871a-11eb-9956-52e64fa2ccc7.png)
Did not work with
```
uses: bogaertg/action-slack-notify@fix/remove-default-value-slack-webhook
```

**Comment by bogaertg** [comment]
Can you try again ?
it was a mistake on my side

**Comment by Pyppe** [comment]
Seems to work 👍

### Workflow configuration
```yaml
- name: Slack Notification
  uses: bogaertg/action-slack-notify@fix/remove-default-value-slack-webhook
  env:
    MSG_MINIMAL: true
    SLACK_COLOR: danger
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    SLACK_TITLE: INFO for `${{ github.ref }}`
    SLACK_CHANNEL: '#systemtests'
    SLACK_MESSAGE: |
      See details: <${{ env.REPO_URL }}/commit/${{ github.sha }}|(Commit)> <${{ env.REPO_URL }}/actions/runs/${{ github.run_id }}|(Action run)>
    SLACK_FOOTER: ''
```

### Slack post
![image](https://user-images.githubusercontent.com/503168/111495950-84c79700-8748-11eb-96d9-d5aab75943ea.png)
