### ISSUE TITLE
Does not work on ARM self hosted runners.

### ISSUE THREAD

**Issue by mrmachine** [rtCamp/action-slack-notify#83]
```
Run rtCamp/action-slack-notify@v2
  env:
    IMAGE_REPO: ***/***
    IMAGE_TAG: sha-c8a3b726c80f7a55cd22e5d4f4bf578dec90acf5
    SLACK_COLOR: success
    SLACK_WEBHOOK: ***
/usr/bin/docker run --name ghcriortcampactionslacknotifyv213_d2b458 --label c3f261 --workdir /github/workspace --rm -e IMAGE_REPO -e IMAGE_TAG -e SLACK_COLOR -e SLACK_WEBHOOK -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/ubuntu/stacks/system/github-actions-work/4dbfa5e3e9149/_temp/_github_home":"/github/home" -v "/home/ubuntu/stacks/system/github-actions-work/4dbfa5e3e9149/_temp/_github_workflow":"/github/workflow" -v "/home/ubuntu/stacks/system/github-actions-work/4dbfa5e3e9149/_temp/_runner_file_commands":"/github/file_commands" -v "/home/ubuntu/stacks/system/github-actions-work/4dbfa5e3e9149/***/***":"/github/workspace" ghcr.io/rtcamp/action-slack-notify:v2.1.3
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
```

**Comment by Bubbassauro** [comment]
Works when specifying the runner for the slack step, adding:

```yaml
runs-on: ubuntu-latest
```

Example from the documentation:

```yaml
on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
 ```
