### ISSUE TITLE
Unable to get SLACK_ICON or SLACK_ICON_EMOJI to work

### ISSUE THREAD

**Issue by jmeridth** [rtCamp/action-slack-notify#90]
`SLACK_ICON`

github action env vars

![Screen Shot 2021-05-08 at 11 03 38 PM](https://user-images.githubusercontent.com/35014/117560257-b296d100-b051-11eb-9bb2-2cab270d5074.png)

https://github.com/jmeridth?size=48 is a valid image

results

![Screen Shot 2021-05-08 at 11 03 48 PM](https://user-images.githubusercontent.com/35014/117560259-baef0c00-b051-11eb-8436-753aa6229a5e.png)

---

`SLACK_ICON_EMOJI`

github action env vars

![Screen Shot 2021-05-08 at 10 59 39 PM](https://user-images.githubusercontent.com/35014/117560261-c5a9a100-b051-11eb-966e-fa8195e0017c.png)

results (I think this is a result of #89)

![Screen Shot 2021-05-08 at 11 00 43 PM](https://user-images.githubusercontent.com/35014/117560263-d8bc7100-b051-11eb-917b-8da76ddac0b6.png)

Both keep just showing the app icon.

What am I doing wrong?

Thank you for any assistance you can provide.  Cheers.

**Comment by jmeridth** [comment]
The step in my github actions file

```yaml
- name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: our-channel-name
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON_EMOJI: ${{ fromJSON('[":x:", ":white_check_mark:"]')[job.status == 'success'] }}
        SLACK_MESSAGE: "Deploy ${{ fromJSON('[\"FAILED\", \"SUCCEEDED\"]')[job.status == 'success'] }}"
        SLACK_TITLE: 'Application Deployment: Production Environment'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }
        SLACK_FOOTER: 'Powered by our Terraform automated deploys'
```
