### ISSUE TITLE
Unable to disable Vault integration

### ISSUE THREAD

**Issue by FalconerTC** [rtCamp/action-slack-notify#95]
I have a workflow that contains the following

```
...
      - name: Import secrets
        uses: hashicorp/vault-action@v2.1.2
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          exportToken: true
          secrets: |
            ...
...
      - name: Send event to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: <channel>
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
```

I use the Vault action early in the workflow and export the token, but I don't want to use vault with action-slack-notify. Any way of disabling it with config or a different env, or should I just wipe the VAULT_TOKEN env before calling this action?
